/*
 * 
 *  Copyrigh 2008 Gastón Silva
 *  This program is distributed under the terms of the GNU General Public License
 * 
 *  This file is part of ConkyGUI.
 * 
 *  ConkyGUI is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ConkyGUI is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Conky GUI.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

package custom.swing;

import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author  gaston
 */
public class InformationPanel extends JPanel {
    
    private Dimension defaultDimension = new Dimension(InformationPopup.WIDTH, InformationPopup.HEIGHT);

    /** Creates new form InformationPanel */
    public InformationPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelWhite = new javax.swing.JPanel();
        jLabelMessage = new javax.swing.JLabel();

        setMaximumSize(this.defaultDimension);
        setMinimumSize(this.defaultDimension);
        setName("Form"); // NOI18N
        setPreferredSize(this.defaultDimension);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(controllers.ConkyGUI.class).getContext().getResourceMap(InformationPanel.class);
        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanelWhite.setBackground(resourceMap.getColor("jPanelWhite.background")); // NOI18N
        jPanelWhite.setName("jPanelWhite"); // NOI18N

        jLabelMessage.setFont(resourceMap.getFont("jLabelMessage.font")); // NOI18N
        jLabelMessage.setText(resourceMap.getString("jLabelMessage.text")); // NOI18N
        jLabelMessage.setName("jLabelMessage"); // NOI18N
        jPanelWhite.add(jLabelMessage);

        add(jPanelWhite, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

public void setMessage(String message) {
    this.jLabelMessage.setText("File saved");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelWhite;
    // End of variables declaration//GEN-END:variables

}
